version: $(ShortVersion).{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  ShortVersion: 2.0
  VersionSuffix: alfa
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd build
    
    .\build.ps1
