version: $(ShortVersion).{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
environment:
  ShortVersion: 5.0
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd build
    
    .\build.ps1
artifacts:
- path: build\artifacts\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: JvChdNsqHwrRXlRWMWvgzh7PwoArhGYrcavvKvpNG9Qnu7iV2e2J4Oi4YFXmTjRN
  skip_symbols: true

 