version: $(ShortVersion).{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  ShortVersion: 2.2
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd build
    
    .\build.ps1
artifacts:
- path: build\artifacts\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: oy2p63tjiv3wopujjq4a65iq4auh4dmehez7kyzxzu4vhq
  skip_symbols: true